### Recuperar todos los libros

GET http://localhost:1234/books HTTP/1.1


### Recuperar un libro

GET http://localhost:1234/books/crimen-y-castigo HTTP/1.1


### Recuperar los libros por un género

GET http://localhost:1234/books?genre=aventura HTTP/1.1


### Crear un libro

POST http://localhost:1234/books HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "year": 1859,
    "characters": [
"Sindney Carton",
    "Doctor Manette",
    "Lucía Mannette",
    "Carlos Darnay",

    ],
    "name": "Historia de dos Ciudades",
    "image": "historia-de-dos-ciudades.avif",
    "description": "Historia que se desarrolla en dos ciudades: Francia e Inglaterra",
    "summary": "La novela desarolla el complejo tiempo de la revolución francesa",
    "author": "Charles Dickens",
    "conflict": "individuo vs convenciones sociales",
    "genre":["histórico"],
    "slug": "historia-de-dos-ciudades"
  }


### Actualizar un libro por su id

PATCH http://localhost:1234/books/46 HTTP/1.1
Content-Type: application/json

{
  "author": "desconocido",
  "year": 1859
}


### Borrar un libro por su id

DELETE http://localhost:1234/books/22 HTTP/1.1
Content-Type: application/json
